@if ($paginator->hasPages())
	<x-forms.container_call_to_action>
		<div>
			@if (!$paginator->onFirstPage())
				<x-forms.button
					theme="contrast"
					type="button"
					wire:click="previousPage"
				>
					Zurück
				</x-forms.button>
			@else
				<x-forms.button
					disabled
					theme="contrast"
					type="button"
				>
					Zurück
				</x-forms.button>
			@endif
		</div>
		<div>
			@if (!$paginator->onLastPage())
				<x-forms.button
					theme="contrast"
					type="button"
					wire:click="nextPage"
				>
					Nächste
				</x-forms.button>
			@else
				<x-forms.button
					disabled
					theme="contrast"
					type="button"
				>
					Nächste
				</x-forms.button>
			@endif
		</div>
	</x-forms.container_call_to_action>
@endif
